[Interface]
Address = 172.28.255.17/32
DNS = 172.28.255.1
PrivateKey = oKKoQJ75h+xBYvkKC84549Q1cpbRZLLBI9qy5B5TWHY=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:8080
PersistentKeepalive = 25
PublicKey = lrEn7QcikL1LnioJPX1wcPP2uBXrBhxCjDA7LmMfbVU=
