[Interface]
Address = 172.26.255.3/32
DNS = 172.26.255.1
PrivateKey = ODXHAVmbTApb7Iz8aezNO/6PKE9o5GnFKo++R7eTz1A=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = NKlDThhpF30m4MatLz2ZN1lcMBgA1UpyF/9CA+LnazU=
