[Interface]
Address = 172.31.255.20
DNS = 172.31.255.1
PrivateKey = OINmEv8UKXBGdNFq2B2v0WFeEq580H1PMUOnR/5gHXQ=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:80
PersistentKeepalive = 25
PublicKey = KwoNe6wYBva41TfOFI2/aKNjW4jtx8U+XmO4v5mvTSA=
