[Interface]
Address = 172.28.255.7/32
DNS = 172.28.255.1
PrivateKey = AMqAf3LMZG06cetjrYcy6xAXedW57GgndUBuikZsp10=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:8080
PersistentKeepalive = 25
PublicKey = lrEn7QcikL1LnioJPX1wcPP2uBXrBhxCjDA7LmMfbVU=
