[Interface]
Address = 172.25.255.21/32
DNS = 172.25.255.1
PrivateKey = GCS/A4aXe3rI9CrXcfzWC5DW07hP9KNRYr0VlDjs73w=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:80
PersistentKeepalive = 25
PublicKey = M+3aJ8ldfrbB/+wU0vQCR/RILt2lJIUSjRFHhxiJ2hw=
