[Interface]
Address = 172.26.255.14/32
DNS = 172.26.255.1
PrivateKey = 4HbrCMidHLHJ6BVJWge7IWFGF0/zjrPTjDR28euI+1k=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = NKlDThhpF30m4MatLz2ZN1lcMBgA1UpyF/9CA+LnazU=
