[Interface]
Address = 172.26.255.8/32
DNS = 172.26.255.1
PrivateKey = IPa9aE4zk9hxV7k4SkvNq01XjGImV//psu52doLhImc=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = NKlDThhpF30m4MatLz2ZN1lcMBgA1UpyF/9CA+LnazU=
