[Interface]
Address = 172.28.255.16/32
DNS = 172.28.255.1
PrivateKey = MMto8Qt8jY8LlWakIjXTtWN4KLJfAExXVszDSfTgoVs=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:8080
PersistentKeepalive = 25
PublicKey = lrEn7QcikL1LnioJPX1wcPP2uBXrBhxCjDA7LmMfbVU=
