[Interface]
Address = 172.27.255.7/32
DNS = 172.27.255.1
PrivateKey = 0I9D/f1484pl8HWCsoU1pE3Gkft9w1/lmXU3A18tnGg=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:4500
PersistentKeepalive = 25
PublicKey = xGwmda/kiSexfth3os+R2bcbWSPi+eedEm5hW3gO6Qs=
