[Interface]
Address = 172.28.255.4/32
DNS = 172.28.255.1
PrivateKey = uAz2xYCj7NkPZy1JlZBC3M3NNNK0dTTgWCA5pQx9UVs=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:8080
PersistentKeepalive = 25
PublicKey = lrEn7QcikL1LnioJPX1wcPP2uBXrBhxCjDA7LmMfbVU=
