[Interface]
Address = 172.26.255.16/32
DNS = 172.26.255.1
PrivateKey = cKcMS1nVONmLg2BFtqR3NWOadfDZC3MxQ55UOMBAUk4=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = NKlDThhpF30m4MatLz2ZN1lcMBgA1UpyF/9CA+LnazU=
