[Interface]
Address = 172.30.255.12
DNS = 172.30.255.1
PrivateKey = mNDMfnv8vNUTtobZ7A/7Zs4RXOUFcrEM41JLr6RssVE=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = Rqpn4yw11hjea0EmP4mxWzmHx1ybuetCtGG8oxPs1wM=
