base {
	log_debug = off;
	log_info = off;
        log = "file:/etc/redsocks/redsocks.log";
	daemon = on;
	user = redsocks;
	group = redsocks;
	redirector = iptables;
        redsocks_conn_max = 32768;
        connpres_idle_timeout = 7440;
        max_accept_backoff = 6000;
}

redsocks {
        local_ip = 172.29.255.1;
        local_port = 8080;
        ip = 172.29.255.1;
        port = 1080;
        type = socks5;
        }

redsocks {
        local_ip = 172.29.255.1;
        local_port = 8081;
        ip = 172.29.255.1;
        port = 1081;
        type = socks5;
        }

redsocks {
        local_ip = 172.29.255.1;
        local_port = 8082;
        ip = 172.29.255.1;
        port = 1082;
        type = socks5;
        }


redsocks {
        local_ip = 172.29.255.1;
        local_port = 8083;
        ip = 172.29.255.1;
        port = 1083;
        type = socks5;
        }

