[Interface]
Address = 172.26.255.18/32
DNS = 172.26.255.1
PrivateKey = 8GEdzmvaS21jQo7aADrbKw1Gl7nER61p5AYJIgRI9mU=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = NKlDThhpF30m4MatLz2ZN1lcMBgA1UpyF/9CA+LnazU=
