[Interface]
Address = 172.27.255.4/32
DNS = 172.27.255.1
PrivateKey = CODozoa9fIA8/v4M1REeEBKhO6haENPH5wzIAw0Dx3U=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:4500
PersistentKeepalive = 25
PublicKey = xGwmda/kiSexfth3os+R2bcbWSPi+eedEm5hW3gO6Qs=
