[Interface]
Address = 172.28.255.20/32
DNS = 172.28.255.1
PrivateKey = SIerienSGGEoBQosawOVijVyGr3P6rPgk99i7MrfcEo=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:8080
PersistentKeepalive = 25
PublicKey = lrEn7QcikL1LnioJPX1wcPP2uBXrBhxCjDA7LmMfbVU=
