[Interface]
Address = 172.30.255.3
DNS = 172.30.255.1
PrivateKey = EEmTs8ynIpZGuxT/bSMQGkLn64aRZdqX+rB/BNH+L0k=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = Rqpn4yw11hjea0EmP4mxWzmHx1ybuetCtGG8oxPs1wM=
