[Interface]
Address = 172.27.255.16/32
DNS = 172.27.255.1
PrivateKey = EG6iSwuzQzIfz4qwQ9p7yQiUolv3Mtrz6kSv46B6h2U=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:4500
PersistentKeepalive = 25
PublicKey = xGwmda/kiSexfth3os+R2bcbWSPi+eedEm5hW3gO6Qs=
