[Interface]
Address = 172.28.255.3/32
DNS = 172.28.255.1
PrivateKey = wEY9SfzslFRZRfEmS08+rcqbl1jUlC/gdsJBcfGLbk0=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:8080
PersistentKeepalive = 25
PublicKey = lrEn7QcikL1LnioJPX1wcPP2uBXrBhxCjDA7LmMfbVU=
