[Interface]
Address = 172.25.255.9/32
DNS = 172.25.255.1
PrivateKey = ILi75WsrA0JoS1mhJ5tMF1ATmPf9Uw/IQsp4ZNS6H1E=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:80
PersistentKeepalive = 25
PublicKey = M+3aJ8ldfrbB/+wU0vQCR/RILt2lJIUSjRFHhxiJ2hw=
