[Interface]
Address = 172.26.255.6/32
DNS = 172.26.255.1
PrivateKey = aH5btXF2xaqI78gg2+yhnAWZ250pziq+bfv7WRywmHw=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = NKlDThhpF30m4MatLz2ZN1lcMBgA1UpyF/9CA+LnazU=
