[Interface]
Address = 172.27.255.13/32
DNS = 172.27.255.1
PrivateKey = gBNXT/eJs+TB072nbcGDpA2b7CjrZ+K0yjC5SDsFAWc=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:4500
PersistentKeepalive = 25
PublicKey = xGwmda/kiSexfth3os+R2bcbWSPi+eedEm5hW3gO6Qs=
