[Interface]
Address = 172.25.255.5/32
DNS = 172.25.255.1
PrivateKey = WA4MC8TcaK6+MoDnUwYJFoHo8GUBbVtEYtsTzC4a6FM=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:80
PersistentKeepalive = 25
PublicKey = M+3aJ8ldfrbB/+wU0vQCR/RILt2lJIUSjRFHhxiJ2hw=
