[Interface]
Address = 172.30.255.14/32
DNS = 172.30.255.1
PrivateKey = sMnqVe2cg9ZqEsXUjU9/c8/M9SmgXMI1SIT3OobWlHM=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = Rqpn4yw11hjea0EmP4mxWzmHx1ybuetCtGG8oxPs1wM=



