[Interface]
Address = 172.25.255.11/32
DNS = 172.25.255.1
PrivateKey = +OJ+TaZL2miic+/ihwp0H8vlANKlgEddqL3Nc7l+HlE=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:80
PersistentKeepalive = 25
PublicKey = M+3aJ8ldfrbB/+wU0vQCR/RILt2lJIUSjRFHhxiJ2hw=
