[Interface]
Address = 172.26.255.7/32
DNS = 172.26.255.1
PrivateKey = kJKfLg9OM0x7PSWK6oUd3ajNwFUfNPPLQB4XQxFSpn8=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = NKlDThhpF30m4MatLz2ZN1lcMBgA1UpyF/9CA+LnazU=
