[Interface]
Address = 172.27.255.15/32
DNS = 172.27.255.1
PrivateKey = 4BeysmKBwXlwO19J5yWTqKBqAx3TOn9aRr8Gx5VEQEY=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:4500
PersistentKeepalive = 25
PublicKey = xGwmda/kiSexfth3os+R2bcbWSPi+eedEm5hW3gO6Qs=
