[Interface]
Address = 172.25.255.20/32
DNS = 172.25.255.1
PrivateKey = 4FDdq9fjaUKj7xtyDso5RHg23h/xnUuWvE8v9UnUTkI=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:80
PersistentKeepalive = 25
PublicKey = M+3aJ8ldfrbB/+wU0vQCR/RILt2lJIUSjRFHhxiJ2hw=
