[Interface]
Address = 172.30.255.2/32
DNS = 172.30.255.1
PrivateKey = QMU1tNjnU1KJqelksKLEeRlhiJd6evhZvVm2tyNeK1c=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = Rqpn4yw11hjea0EmP4mxWzmHx1ybuetCtGG8oxPs1wM=



