[Interface]
Address = 172.28.255.13/32
DNS = 172.28.255.1
PrivateKey = oIiWM6Z9waPTJUKTUn9Infal5tKCBQsNoAY0LrSqo0U=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:8080
PersistentKeepalive = 25
PublicKey = lrEn7QcikL1LnioJPX1wcPP2uBXrBhxCjDA7LmMfbVU=
