[Interface]
Address = 172.25.255.8/32
DNS = 172.25.255.1
PrivateKey = eNCZ04Y6aUEdOR0ySJNjWwKoQIsJlO0cEUj/5mWGl0w=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:80
PersistentKeepalive = 25
PublicKey = M+3aJ8ldfrbB/+wU0vQCR/RILt2lJIUSjRFHhxiJ2hw=
