[Interface]
PrivateKey = uN3gIzSDn7h7Re5cdSD+JSU8bInda8EA0xEx+/7Ng3w=
Address = 172.25.255.1/24
ListenPort = 80

# client01
[Peer]
PublicKey = qrhzsyyPmS/Zu5jxXRvmjIIvbVeyLSK8d13xyGVDm3Y=
AllowedIPs = 172.25.255.2

# client02
[Peer]
PublicKey = EQrn1p7Egl8m9m+VvbpKCG5Udm3QgZcCXwX6FPIEsgQ=
AllowedIPs = 172.25.255.3

# client03
[Peer]
PublicKey = y75HU6/jiJtn+7d+fVM6talJVe7IYtqAB8YLJg6LkDY=
AllowedIPs = 172.25.255.4

# client04
[Peer]
PublicKey = dg14vNXj1cSjCCmv/wi7C5PEz7RZQzmGw2Ves2PUVyU=
AllowedIPs = 172.25.255.5

# client05
[Peer]
PublicKey = XnOGWCAoR4BfiduXJkWcDeWenSTxl9goOMRtGChepjY=
AllowedIPs = 172.25.255.6

# client06
[Peer]
PublicKey = 9DrwK/YsSHFwmStzyxQDFp/D426Xxj4i/+1VwmHZdXQ=
AllowedIPs = 172.25.255.7

# client07
[Peer]
PublicKey = MJBTcO8tDFVtJF/sbOi6GomnLAn2RoduB/Ges+yzZEA=
AllowedIPs = 172.25.255.8

# client08
[Peer]
PublicKey = lfL8QxiD5kR9xIjw5W57CLIeX+FBI68+KVgmFCn1ZQE=
AllowedIPs = 172.25.255.9

# client09
[Peer]
PublicKey = WvX/7nUF1wnM0Pw/VAmKuEcDN1Hdgdz1qKNPJwRwsEk=
AllowedIPs = 172.25.255.10

# client10
[Peer]
PublicKey = lm8seBqrbSQ19QyLZMTo4zCtGvcbHbiS+4O//72zi2U=
AllowedIPs = 172.25.255.11

# client11
[Peer]
PublicKey = HhPjziv2Ra2An16AMBmV3SIngt6ZmBD+cvoEVX6p10k=
AllowedIPs = 172.25.255.12

# client12
[Peer]
PublicKey = p09BqXIte0RWeCKihEo6QeVTp+kZm53JSq3JqMepXjc=
AllowedIPs = 172.25.255.13

# client13
[Peer]
PublicKey = BQd+/6NjMHK6OjE4awnSafw64StbEQMGc16NAOGh8FM=
AllowedIPs = 172.25.255.14

# client14
[Peer]
PublicKey = eF9yvrTQaYllSzMSaUP/4DtKSMh3VChybwezjO9cSxI=
AllowedIPs = 172.25.255.15

# client15
[Peer]
PublicKey = nj9RS6H3B09weRS/vd1tPi1sotO6j4YncOuEEZVBBBg=
AllowedIPs = 172.25.255.16

# client16
[Peer]
PublicKey = 0V1SLl5o+b+Hg0C275SKEiWjKxndX/TRXsFGEEAf4zU=
AllowedIPs = 172.25.255.17

# client17
[Peer]
PublicKey = wqHeQQA48+ulvUeboChEVx+g1zsNB7GktZxcWWyTeDs=
AllowedIPs = 172.25.255.18

# client18
[Peer]
PublicKey = QCtN2C7pwEZY2dJ06g8nK5bQCbtE4YuS/XqkMYxUxyA=
AllowedIPs = 172.25.255.19

# client19
[Peer]
PublicKey = lV44sE4bWQ4H+8MUocs9RPCgMt8T4SCsrYx3qkl3ciM=
AllowedIPs = 172.25.255.20

# client20
[Peer]
PublicKey = BwNPt2F9ytCKm+kzOCIMHWyM5Tn1RVlATj/wrsxEyWo=
AllowedIPs = 172.25.255.21

