[Interface]
PrivateKey = IFqoVpEk83wj9VLZIJtHIfg0h4/+7RM/R6IqNklpHV0=
Address = 172.26.255.1/24
ListenPort = 443

# client01
[Peer]
PublicKey = cx3FW+rQujysDoiBYaPm6+VbStlIPaVQJyClGttOwW8=
AllowedIPs = 172.26.255.2

# client02
[Peer]
PublicKey = IQM/Q7Q+9ShWkESYxurDdjckGN+NJ5lkYwXYUJijxnM=
AllowedIPs = 172.26.255.3

# client03
[Peer]
PublicKey = NJY9sH7lOeqAcyRy/pc9TVCk/GKFadrAocqv4Sb2CgQ=
AllowedIPs = 172.26.255.4

# client04
[Peer]
PublicKey = BZVRUAFNUtz9mhthJsIPQ5yjF4me3VSY6D4Hz/hOsxY=
AllowedIPs = 172.26.255.5

# client05
[Peer]
PublicKey = BLc9sy+bngVgKpK1iYm1nyJbOgGhMh9DggwYJagnflw=
AllowedIPs = 172.26.255.6

# client06
[Peer]
PublicKey = lFq6fsjgV9phEb/+dnL6oOMu6GVjFkeMQSXXeYTepkg=
AllowedIPs = 172.26.255.7

# client07
[Peer]
PublicKey = kgjUg5MoeD+VZM787GUIkvbSFFUBUudMjQK843WfACY=
AllowedIPs = 172.26.255.8

# client08
[Peer]
PublicKey = XMCWTu+kK1tgWRXJxsVkh+/yxGB53cA4qjVZtBu+0FI=
AllowedIPs = 172.26.255.9

# client09
[Peer]
PublicKey = xceaIls6MWV3DOsLOlIfSqtXiYkUEY5jgl+UVPPktAk=
AllowedIPs = 172.26.255.10

# client10
[Peer]
PublicKey = jv8pKtLKxl+zeuh6LacE8v8fELhiAfrlHU/h6si4+UM=
AllowedIPs = 172.26.255.11

# client11
[Peer]
PublicKey = r2IvhWWLU8LzYvjDJchYaudqSKoEEvU4FPlO8xWjrVI=
AllowedIPs = 172.26.255.12

# client12
[Peer]
PublicKey = gZxwrk98f27DafNAcsKVRWiL+h5rsHzL+4iUxPquhCU=
AllowedIPs = 172.26.255.13

# client13
[Peer]
PublicKey = 1UA+GXiuL6XIHvpcOJUPpCP0f52PqwqdNlkjqYIcvA4=
AllowedIPs = 172.26.255.14

# client14
[Peer]
PublicKey = f3fxDgQFFxHFgpqLXB5gU7k7g4F/35atbxEIYj+9nQo=
AllowedIPs = 172.26.255.15

# client15
[Peer]
PublicKey = QhfHqTm2/Y8cLNAe4JJHH55iEhvoE5oOupbS2rHTaRU=
AllowedIPs = 172.26.255.16

# client16
[Peer]
PublicKey = F+tuPJ047WPKUuBqwfBzoZo47CP7vyPOhH8Uwt3IPSk=
AllowedIPs = 172.26.255.17

# client17
[Peer]
PublicKey = 0toFSXukbyp8aQTD6OVxrVlZCxU0QWspwdEdy/nzB0U=
AllowedIPs = 172.26.255.18

# client18
[Peer]
PublicKey = 8S1HESUqs28zfmlZBbDqpalY7xsJHYiZIZMTtbraxgg=
AllowedIPs = 172.26.255.19

# client19
[Peer]
PublicKey = mTGk49NjxIOUQ7cQM7QMvtwslJ6rw3ab3pszrRKTLy0=
AllowedIPs = 172.26.255.20

# client20
[Peer]
PublicKey = 1XjR0IRfEjLx4Qf/SymX8lZq4B+1TgKJ6Gb3YVmmfDM=
AllowedIPs = 172.26.255.21

