[Interface]
PrivateKey = 6D5wcaALNCQZ68FraiauR1juB4Ra+E9jZapjmTD8RmE=
Address = 172.27.255.1/24
ListenPort = 4500

# client01
[Peer]
PublicKey = /YLFGtN0R6xf/mE2YY9h6kWCQWZIssdAuyVIvURZwF0=
AllowedIPs = 172.27.255.2

# client02
[Peer]
PublicKey = 4ecEBNW+0LMsqkOZdrug1O0NA9PXcoPNCseTBAh7MjI=
AllowedIPs = 172.27.255.3

# client03
[Peer]
PublicKey = 9ua8iXhd5b/p/+7YaICQDpNUuIfJJ7V8IgaY4IcaKzE=
AllowedIPs = 172.27.255.4

# client04
[Peer]
PublicKey = 0ibuwqI1AMyjphInfPDYjRA/5O5gdExGzgl1cidvkzw=
AllowedIPs = 172.27.255.5

# client05
[Peer]
PublicKey = C0rzrwI7yfP4/mO/E91C63ePrdJLsm8Hy0/AnulRszg=
AllowedIPs = 172.27.255.6

# client06
[Peer]
PublicKey = HSwX7WlS7wjhi7NHQOLQCalpUnbJ4eo76n3l49iqqDA=
AllowedIPs = 172.27.255.7

# client07
[Peer]
PublicKey = AqwA+5HlOt+a7irWAauC4EUiAq9QcbzLPVFRezoMaXE=
AllowedIPs = 172.27.255.8

# client08
[Peer]
PublicKey = q133tOq+v8U+k2aO3SwQnRykP5CvgKf8kq5OjxjOfRs=
AllowedIPs = 172.27.255.9

# client09
[Peer]
PublicKey = DQf0/tVd79Rj6TCJvdaKGSuCv+Hqk/9+TdExiJLFEQs=
AllowedIPs = 172.27.255.10

# client10
[Peer]
PublicKey = AVd74qaPbzPXHk6YhiJYALfmOXvRuXJb18iUk9Vh4E0=
AllowedIPs = 172.27.255.11

# client11
[Peer]
PublicKey = d+ET09/LXH5oDrYhhGsQWJPLIgZFoSqMICqllfJythY=
AllowedIPs = 172.27.255.12

# client12
[Peer]
PublicKey = uqArNomPlsU0lWfv7DiIl94JBILzkhqNCKjJuZ6lRgw=
AllowedIPs = 172.27.255.13

# client13
[Peer]
PublicKey = g40F+pv5sCwjSGotAvcNhco18N5wAGDC96W1ZTAYkTc=
AllowedIPs = 172.27.255.14

# client14
[Peer]
PublicKey = WxWltiZ9napBgNlBRWookobiel6MRhPDBXrOPpcIAx8=
AllowedIPs = 172.27.255.15

# client15
[Peer]
PublicKey = 980UUfqMhfSEj7gUGFR8APZCaPmAIb93w0fxP8mkqxg=
AllowedIPs = 172.27.255.16

# client16
[Peer]
PublicKey = i5tzFi4MzaYsdUwAVPP3dXO5VA9k59TMm1s20UgpcjE=
AllowedIPs = 172.27.255.17

# client17
[Peer]
PublicKey = 1i90qNIeGBbsOX8TBrFsy1bT6JMzjpTEoqIAOG28U2s=
AllowedIPs = 172.27.255.18

# client18
[Peer]
PublicKey = 6ie+Xpdtt9d45tWsy7glpRjQ1ouDcryrGLPi5zN9TmI=
AllowedIPs = 172.27.255.19

# client19
[Peer]
PublicKey = 0wIeor63ER+YPR921CY0ZnrTOU6gbG8Wdr261noWEl4=
AllowedIPs = 172.27.255.20

# client20
[Peer]
PublicKey = lvHU0N4sUItFM2gYyxykBbKPxYsBAOpJ49zM57mWuFA=
AllowedIPs = 172.27.255.21

