[Interface]
PrivateKey = qPyZN45ve46H7iApbDfXkm5UXUq1G00VLEaesTXkXUA=
Address = 172.28.255.1/24
ListenPort = 8080

# client01
[Peer]
PublicKey = 68I8IZv+3VnObgHNPlWYR3DNdtRGavlXivd/DMVykQ4=
AllowedIPs = 172.28.255.2

# client02
[Peer]
PublicKey = SPTC9O3lrobi74NGxu95o0YJyJmSbqLSWEGC9kW7+Co=
AllowedIPs = 172.28.255.3

# client03
[Peer]
PublicKey = fNbopnxR/69kXd/CdWbFsMyEtFlCAF+400kj8D1nNzE=
AllowedIPs = 172.28.255.4

# client04
[Peer]
PublicKey = khR64wmOWx8ftRe/8cu3U/xsfkvoxBuuFXm1PNiTBQs=
AllowedIPs = 172.28.255.5

# client05
[Peer]
PublicKey = SMmVHA27P2V35kTWgoz16f3VXyHD6nkDCHDo+o2XzHQ=
AllowedIPs = 172.28.255.6

# client06
[Peer]
PublicKey = x1mpsyldOgshII3YJf7Dt6iFSmnbAQyWniQCKeCRiAE=
AllowedIPs = 172.28.255.7

# client07
[Peer]
PublicKey = qDIlCiX7iIgOtkQy8KlJ2CwsMnN5pUa5HVVfszzZ+BM=
AllowedIPs = 172.28.255.8

# client08
[Peer]
PublicKey = 5IhxSK6DfvqdDJndZKqbaXYh2ErNuXcZtJdQ+gUysUU=
AllowedIPs = 172.28.255.9

# client09
[Peer]
PublicKey = ZGa9mjklPPDQcozTu8xHS+zEr18BNp5Tn69dHg+17yE=
AllowedIPs = 172.28.255.10

# client10
[Peer]
PublicKey = 41tC72CwtJ5o7xYrulChaYDAHo0quBd46nqLBrGc3Ws=
AllowedIPs = 172.28.255.11

# client11
[Peer]
PublicKey = 49jbC3Oyn8BbSNL0v44LPcpcSSDsvOEmDOMWTS6KMHE=
AllowedIPs = 172.28.255.12

# client12
[Peer]
PublicKey = K3avzcml5lht3OCJf9H7CihguyLGwa5mtkE5/zgwljk=
AllowedIPs = 172.28.255.13

# client13
[Peer]
PublicKey = oouYfaOnRQLKIcsoAiwqr37epB8ZwSdrtdFAehkENX0=
AllowedIPs = 172.28.255.14

# client14
[Peer]
PublicKey = ijVCAa1p5HDAwBqAF1BXFnk/af2wk3uL4P5ucaiggko=
AllowedIPs = 172.28.255.15

# client15
[Peer]
PublicKey = eIk03xPi8MmAEwJcVGd1m7wijOVJyaLaQ9dr1zO30U0=
AllowedIPs = 172.28.255.16

# client16
[Peer]
PublicKey = ybeEF5iL9HuZE06VYYzPM+I6nuWfXO+/NeEn5vHSzHg=
AllowedIPs = 172.28.255.17

# client17
[Peer]
PublicKey = +zTfRvM/v3hVNEHnAqKEoeG1ikWquKE3DNuhaOsnBi8=
AllowedIPs = 172.28.255.18

# client18
[Peer]
PublicKey = BhB480yAFBpMw5p6DtLJqWvj0jJ/hbwigomHrC/y0B8=
AllowedIPs = 172.28.255.19

# client19
[Peer]
PublicKey = Fz12h5oqESqDaK9IJv6V4F4hzimv7+Ui0gSUrykUcjk=
AllowedIPs = 172.28.255.20

# client20
[Peer]
PublicKey = T7cVpk/pB/xvI1iYm6ErufP8CQ2QNyoq6X3DEtzqOnQ=
AllowedIPs = 172.28.255.21

