[Interface]
Address = 172.27.255.3/32
DNS = 172.27.255.1
PrivateKey = +PXz8BCrRT47KRRqhTsDrFi2gOoOXtMO0fiiWxfH4nQ=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:4500
PersistentKeepalive = 25
PublicKey = xGwmda/kiSexfth3os+R2bcbWSPi+eedEm5hW3gO6Qs=
