[Interface]
PrivateKey = yBD0PX7XBA0syiLWAd//0sFnAlnmr2vbutH6OsDPFm4=
Address = 172.30.255.1/24
ListenPort = 443

# client01
[Peer]
PublicKey = HwbaCIq2652wbFIF60Q3stHkeZkO4vjArNydpIZ1Hxw=
AllowedIPs = 172.30.255.2

# client02
[Peer]
PublicKey = a1Ro8sVzOHJ5Wp1Ah617kJiA2l9Cal3z7u06G7htrF8=
AllowedIPs = 172.30.255.3

# client03
[Peer]
PublicKey = hoULAMUjIMbrgyudH5UAy/Qc+rGoDZEBjYmkDNyhLXE=
AllowedIPs = 172.30.255.4

# client04
[Peer]
PublicKey = BVDtAzCX9x020mr92Q1QYcmdKx0f+eF6NVVLQ00QMAA=
AllowedIPs = 172.30.255.5

# client05
[Peer]
PublicKey = 3otUHexRzBk/rmi4j4kE6rIYpmz6toMJ9xpYbjg9LmA=
AllowedIPs = 172.30.255.6

# client06
[Peer]
PublicKey = AAqjxKofv3x/F2g8Ke4bUiSFLm/gUjQuZlEBE0+G4g8=
AllowedIPs = 172.30.255.7

# client07
[Peer]
PublicKey = JfJ2Cwzkhg4X1M219eCEV1G4xhvOaWA4vSyXb3EuEQA=
AllowedIPs = 172.30.255.8

# client08
[Peer]
PublicKey = liy74D2XMvOME7i/6ef16LQxMPppWwGZ3CWC4nhScS8=
AllowedIPs = 172.30.255.9

# client09
[Peer]
PublicKey = 3LjTFv7b/cWZYTXC3Mhhux+mr35KtndTRnU/jp6NfWY=
AllowedIPs = 172.30.255.10

# client10
[Peer]
PublicKey = CLAc5hy8B1Cw8GSPakbpJN/mtivqMbJmo+ucak3yPCE=
AllowedIPs = 172.30.255.11

# client11
[Peer]
PublicKey = Jejqr0U4cEOmVdhhMmobAdF0PtlblXiYyTukqZhUNjc=
AllowedIPs = 172.30.255.12

# client12
[Peer]
PublicKey = dMD+KyMhWpVyDGWhaGiDE34YNkeL6FhlatBmeLU6uD0=
AllowedIPs = 172.30.255.13

# client13
[Peer]
PublicKey = z7ppu9hPfHpT/k2NvwDVWZ2e+InJ6wJui8l0syHJw10=
AllowedIPs = 172.30.255.14

# client14
[Peer]
PublicKey = IGFrO8Fko3d1MmUcwvuD7BK/W/U2G3qFY2YwhGb8eAw=
AllowedIPs = 172.30.255.15

# client15
[Peer]
PublicKey = MOx0/cDbxLLuBh0LDrQNpKFb9lAFxHzdDji9dheBHX8=
AllowedIPs = 172.30.255.16

# client16
[Peer]
PublicKey = s04C3T+0wmZduDX2p2Cv3EpYa74cUGFPECfTO/aJ+H8=
AllowedIPs = 172.30.255.17

# client17
[Peer]
PublicKey = 9YjKxCGYCOq1+dyN8m96uELNK4KDx2aZiEto+OiE8A0=
AllowedIPs = 172.30.255.18

# client18
[Peer]
PublicKey = lUjmjtJSGIEwsYUX4l4PiN/JGFTj1FsLhZCpq3FftGk=
AllowedIPs = 172.30.255.19

# client19
[Peer]
PublicKey = d6vKPQOSjEmMe4DPlFsqqnolVH6E5dcR3Hs7TJ3xIWc=
AllowedIPs = 172.30.255.20

# client20
[Peer]
PublicKey = GaQ33pYO+iNca5hBWbCEWjqkEm7SRbtEvlioKi5iEEg=
AllowedIPs = 172.30.255.21




