[Interface]
Address = 172.31.255.8/32
DNS = 172.31.255.1
PrivateKey = wJc3TQjQNYfECn+t19uM+c193NxWNgJ//519cDDOGmU=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:80
PersistentKeepalive = 25
PublicKey = KwoNe6wYBva41TfOFI2/aKNjW4jtx8U+XmO4v5mvTSA=



