[Interface]
Address = 172.30.255.5
DNS = 172.30.255.1
PrivateKey = iCp3IHlg2ERTd7IIoysflL8Og7v1S/+JHmm09DFfVkc=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = Rqpn4yw11hjea0EmP4mxWzmHx1ybuetCtGG8oxPs1wM=
