[Interface]
Address = 172.27.255.12/32
DNS = 172.27.255.1
PrivateKey = 8GcIA7HcS0xEHGb/kKyEewPGC9eCq/d/bP4HqSqokFY=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:4500
PersistentKeepalive = 25
PublicKey = xGwmda/kiSexfth3os+R2bcbWSPi+eedEm5hW3gO6Qs=
