[Interface]
Address = 172.25.255.16/32
DNS = 172.25.255.1
PrivateKey = aPlN6u6lKBky33tE3dZ+fIt+dTTP+0kBosMMwOj/0Xk=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:80
PersistentKeepalive = 25
PublicKey = M+3aJ8ldfrbB/+wU0vQCR/RILt2lJIUSjRFHhxiJ2hw=
