[Interface]
Address = 172.30.255.9
DNS = 172.30.255.1
PrivateKey = 4G69KZzRyF2lLXo/YVU7+WUZ76KewyQdKqImf1e6G1E=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = Rqpn4yw11hjea0EmP4mxWzmHx1ybuetCtGG8oxPs1wM=
