[Interface]
Address = 172.27.255.20/32
DNS = 172.27.255.1
PrivateKey = gDezkEw/3p80Mn5w3g4i0kPFFVMt8YoTOMex+unkMl4=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:4500
PersistentKeepalive = 25
PublicKey = xGwmda/kiSexfth3os+R2bcbWSPi+eedEm5hW3gO6Qs=
