[Interface]
Address = 172.25.255.19/32
DNS = 172.25.255.1
PrivateKey = EGLhydkX3OnOTiOWV1bwldlGHr19PwutS5GTfpSUz1s=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:80
PersistentKeepalive = 25
PublicKey = M+3aJ8ldfrbB/+wU0vQCR/RILt2lJIUSjRFHhxiJ2hw=
