[Interface]
Address = 172.28.255.21/32
DNS = 172.28.255.1
PrivateKey = gMfn/Okl91dbV5IyQ4Jvyke7a2Hp/rQVdjgpmnrGrGY=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:8080
PersistentKeepalive = 25
PublicKey = lrEn7QcikL1LnioJPX1wcPP2uBXrBhxCjDA7LmMfbVU=
