[Interface]
PrivateKey = yKVZG2ve6jl2SE478HA9qkUc45v6iPf9+dxuYrABa1g= 
Address = 172.31.255.1/24
ListenPort = 80

# client01
[Peer]
PublicKey = H8+GoxCyNkE5eVGQ2FlsDIMl697J+X+dgcVDQuuBEjA=
AllowedIPs = 172.31.255.2

# client02
[Peer]
PublicKey = WUsZ9waK3hBM+Dy3V6W2D8QZjrsuODzumUrnI5LWaUc=
AllowedIPs = 172.31.255.3

# client03
[Peer]
PublicKey = jJEFujqSk1BscZS3lKM9cX3CPP4P3GnMHLiDFAGxeQk=
AllowedIPs = 172.31.255.4

# client04
[Peer]
PublicKey = 1jZ3kJDd3Ti8BuMiah9PCKcg2pE8pCCqXTUc28CTbXQ=
AllowedIPs = 172.31.255.5

# client05
[Peer]
PublicKey = cFrlOp82119vMpc0aJBuPL9qMLxsdQH9r1wH2hGNUwE=
AllowedIPs = 172.31.255.6

# client06
[Peer]
PublicKey = xSKftN3nURuaZg6CVwhbTbXYA6uqZAPSzs//RhqXRBQ=
AllowedIPs = 172.31.255.7

# client07
[Peer]
PublicKey = hLlivSCJ648gk/GoI9D0qNOLFkD8my+/kGqFyw3EKDw=
AllowedIPs = 172.31.255.8

# client08
[Peer]
PublicKey = nOmZTPbxwbuNi1DhNLigdjhv1Nxw55tjRIQ2s0+EIH4=
AllowedIPs = 172.31.255.9

# client09
[Peer]
PublicKey = 5ncZ3gB0qIUD1VZs+kcnvWFfV4fXkAWgiL8y1PrkST0=
AllowedIPs = 172.31.255.10

# client10
[Peer]
PublicKey = LvDDu/GfFuqOLb1n6FnyT2FFIAqBtAF0bs8Jov/OSGw=
AllowedIPs = 172.31.255.11

# client11
[Peer]
PublicKey = f4rq+xQDRO74lu28CiRF2v6umON3RXO3XMJuhdedmy4=
AllowedIPs = 172.31.255.12

# client12
[Peer]
PublicKey = sb5pncVwM8KcYyBwLHRDclN57w+h5vWQxsJfRmLT1DQ=
AllowedIPs = 172.31.255.13

# client13
[Peer]
PublicKey = XrequzIvhq83jQ6FECuwsoDgnCGX8wnYoRdQADkoixk=
AllowedIPs = 172.31.255.14

# client14
[Peer]
PublicKey = UJP2n+9nN64o+x5mO3geXdNUB0a7WXcukPsOqZ1pWSs=
AllowedIPs = 172.31.255.15

# client15
[Peer]
PublicKey = 8UVYm1SziQI7AwsA95E4xL788hYU3J64Ahm/Hfk02Bw=
AllowedIPs = 172.31.255.16

# client16
[Peer]
PublicKey = nd54w/JevqFAAd9b3250sgeWA0xGQ0kKIZ7E46wVPSE=
AllowedIPs = 172.31.255.17

# client17
[Peer]
PublicKey = JHU9BsQjApRsPxStQV/ozc3eYQxNUFE83Ic2/GR+JzA=
AllowedIPs = 172.31.255.18

# client18
[Peer]
PublicKey = CHsrmqxDSSprucwNbbsnTaLiQiw4G64NL4/gP4wrE2w=
AllowedIPs = 172.31.255.19

# client19
[Peer]
PublicKey = Jx4MuvSXXlVR7Ag5EVsJLR0/GXwRU/5PErat0/+uekE=
AllowedIPs = 172.31.255.20

# client20
[Peer]
PublicKey = Pclyd2Iw+kNIjA8cB4oJ49Gl3XPl1JcDky+VsqZbsUI=
AllowedIPs = 172.31.255.21

