[Interface]
Address = 172.28.255.8/32
DNS = 172.28.255.1
PrivateKey = UKWTI+lWFDtrn0U0F4kcC+/mOFctdvOZSdB+0lpdYXs=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:8080
PersistentKeepalive = 25
PublicKey = lrEn7QcikL1LnioJPX1wcPP2uBXrBhxCjDA7LmMfbVU=
