[Interface]
Address = 172.31.255.10/32
DNS = 172.31.255.1
PrivateKey = AFKx0+xm6Rh7p+2a2a6ImJ6XHzZ6YAehPjMou1mfoEw=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:80
PersistentKeepalive = 25
PublicKey = KwoNe6wYBva41TfOFI2/aKNjW4jtx8U+XmO4v5mvTSA=



