[Interface]
Address = 172.28.255.5/32
DNS = 172.28.255.1
PrivateKey = SJQW14Jdq4tR0GPIGuI0QrRaTOOQ2ZpHJ7SDDb927VM=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:8080
PersistentKeepalive = 25
PublicKey = lrEn7QcikL1LnioJPX1wcPP2uBXrBhxCjDA7LmMfbVU=
