[Interface]
Address = 172.31.255.15/32
DNS = 172.31.255.1
PrivateKey = QMWzNT4mJ0MnbH4KGMJJGymLOUqg+dFpiNo6vE6JhkA=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:80
PersistentKeepalive = 25
PublicKey = KwoNe6wYBva41TfOFI2/aKNjW4jtx8U+XmO4v5mvTSA=



