[Interface]
Address = 172.28.255.15/32
DNS = 172.28.255.1
PrivateKey = 6NFsx9qyO8U55ghG20fJQN4/0An088CMOyDbNSoz13I=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:8080
PersistentKeepalive = 25
PublicKey = lrEn7QcikL1LnioJPX1wcPP2uBXrBhxCjDA7LmMfbVU=
