[Interface]
Address = 172.26.255.5/32
DNS = 172.26.255.1
PrivateKey = iAC1fYIUY34k9/n/Ha72/e1ETGtwIWaMVke8vGqGqlk=
[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = NKlDThhpF30m4MatLz2ZN1lcMBgA1UpyF/9CA+LnazU=
