[Interface]
Address = 172.26.255.15/32
DNS = 172.26.255.1
PrivateKey = GNFwcSwPR1KZXbgKRJZYfjF9Dz8mD3fhsIFnysPQZEk=
[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = your-own-ddns-name.ddnsfree.com:443
PersistentKeepalive = 25
PublicKey = NKlDThhpF30m4MatLz2ZN1lcMBgA1UpyF/9CA+LnazU=
